name: Trigger auto deployment for kernel-memory

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/kernel-memory-AutoDeployTrigger-464cfc27-ab95-4c2d-b8fd-8f7080eedeaf.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KERNELMEMORY_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/App/kernel-memory
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: caf1801bb5e5acr.azurecr.io
          registryUsername: ${{ secrets.KERNELMEMORY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KERNELMEMORY_REGISTRY_PASSWORD }}
          containerAppName: kernel-memory
          resourceGroup: rg-deploymentlab
          imageToBuild: caf1801bb5e5acr.azurecr.io/kernel-memory:${{ github.sha }}
          
            

     

